import { useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { technologies, technologyCategories } from '@/data/technologies';
import { SectionHeading } from '@/components/SectionHeading';

export function SkillsSection() {
  const [active, setActive] = useState<(typeof technologyCategories)[number]>('Frontend');
  const items = technologies.filter((technology) => technology.category === active);
  return <section id="skills" className="section-padding bg-elev"><div className="section-container"><SectionHeading eyebrow="The toolkit" title="Tools for building the whole thing." description="A practical stack chosen for speed, reliability, and the freedom to build from interface to infrastructure." /><div className="mt-12 grid gap-8 lg:grid-cols-[220px_1fr]"><div className="flex gap-2 overflow-x-auto lg:flex-col lg:overflow-visible">{technologyCategories.map((category) => <button key={category} type="button" onClick={() => setActive(category)} className={`flex shrink-0 items-center justify-between rounded-lg px-4 py-3 text-left text-sm font-medium transition-colors ${active === category ? 'bg-card text-fg shadow-sm' : 'text-muted hover:text-fg'}`}><span>{category}</span>{active === category && <ArrowUpRight size={15} className="text-accent-500" />}</button>)}</div><div className="grid gap-3 sm:grid-cols-2"><div className="col-span-full mb-2 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted">{active} / {String(items.length).padStart(2, '0')} technologies</span><span className="h-px w-20 bg-border-base" /></div>{items.map((technology) => <div key={technology.name} className="group flex items-center gap-4 rounded-xl border border-base bg-card p-4 transition-all hover:-translate-y-0.5 hover:border-accent-500/40"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-base font-mono text-xs font-semibold" style={{ color: technology.color }}>{technology.name.slice(0, 2).toUpperCase()}</span><div><h3 className="text-sm font-semibold text-fg">{technology.name}</h3><p className="mt-1 text-xs text-muted">{technology.description}</p></div></div>)}</div></div></div></section>;
}
